// react-package/src/App.js
import React, { useState } from 'react';
import { AgGridReact } from 'ag-grid-react';

import 'ag-grid-community/dist/styles/ag-grid.css';
import 'ag-grid-community/dist/styles/ag-theme-alpine.css';

import 'ag-grid-enterprise'

const App = () => {
  const [rowData] = useState([
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxter", price: 72000 }
  ]);

  const [columnDefs] = useState([
    { field: 'make', enableRowGroup: true },
    { field: 'model', enableRowGroup: true },
    { field: 'price', aggFunc: 'sum' }
  ]);

  const [gridOptions] = useState(
    {
      defaultColDef: {
        filter: true,
        enableRowGroup: true,
      },
      rowGroupPanelShow: 'always'
    });

  return (
    <div className="ag-theme-alpine" style={{ height: 400, width: 600 }}>
      <AgGridReact
        gridOptions={gridOptions}
        rowData={rowData}
        columnDefs={columnDefs}
      >
      </AgGridReact>
    </div>
  );
};

export default App;

// vue-module/src/App.vue


<template>
  <ag-grid-vue
    style="width: 500px; height: 500px"
    class="ag-theme-alpine"
    :gridOptions="gridOptions"
    :columnDefs="columnDefs"
    :rowData="rowData"
  >
  </ag-grid-vue>
</template>


<script>
import { AgGridVue } from "@ag-grid-community/vue3";

export default {
  name: "App",
  components: {
    AgGridVue,
  },
  setup() {
    return {
      columnDefs: [
        { field: "make", enableRowGroup: true },
        { field: "model", enableRowGroup: true },
        { field: "price", aggFunc: "sum" },
      ],

      rowData: [
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 },
      ],

      gridOptions: {
        defaultColDef: {
          filter: true,
          enableRowGroup: true,
        },
        rowGroupPanelShow: "always",
      },
    };
  },
};
</script>

<style lang="scss">
@import "~@ag-grid-community/core/dist/styles/ag-grid.css";
@import "~@ag-grid-community/core/dist/styles/ag-theme-alpine.css";
</style>
